site_name: product-fun
site_url: https://github.com/yashagarwal1994/product-fun
site_author: Product.fun
site_description: Create and run agents and functions on Product.fun

repo_name: yashagarwal1994/product-fun
repo_url: https://github.com/yashagarwal1994/product-fun

copyright: Copyright (c) 2023-present Product.fun <yash@nurturelabs.co>

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

plugins:
  - search:
  - git-revision-date-localized:
      type: timeago
      enable_creation_date: true
  - mkdocstrings:

extra:
  social:
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/product-fun/
    - icon: fontawesome/brands/github
      link: https://github.com/yashagarwal1994
    # - icon: fontawesome/brands/twitter
    #   link: https://twitter.com/REPLACE_TWITTER_USERNAME
    # - icon: fontawesome/brands/linkedin
    #   link: https://www.linkedin.com/in/REPLACE_LINKEDIN_USERNAME/

nav:
  - Home: index.md
  - License: license.md
