site_name: Agentopia
site_url: https://docs.agentopia.xyz
site_author: Yash Agarwal
site_description: On-demand Services/Data marketplace for AI Agents
repo_name: nurturelabs-co/Agentopia
repo_url: https://github.com/nurturelabs-co/Agentopia

copyright: Copyright (c) 2023-present Agentopia <yash@nurturelabs.co>
theme:
  name: material
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/lightbulb-auto
      name: Switch to light mode
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: black
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: black
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to system preference
  features:
  - content.code.annotate
  - content.code.copy
  # - content.code.select
  - content.footnote.tooltips
  - content.tabs.link
  - content.tooltips
  - navigation.footer
  - navigation.indexes
  - navigation.instant
  - navigation.instant.prefetch
  # - navigation.instant.preview
  - navigation.instant.progress
  - navigation.path
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - navigation.tracking
  - search.highlight
  - search.share
  - search.suggest
  - toc.follow
  - content.tabs.link

  icon:
    repo: fontawesome/brands/github-alt
  logo: img/agentopia_logo.png
  favicon: img/agentopia_logo.png
  language: en

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search:
  - git-revision-date-localized:
      type: timeago
      enable_creation_date: true
  - mkdocstrings:

extra:
  social:
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/agentopia/
    - icon: fontawesome/brands/github
      link: https://github.com/nurturelabs-co
    # - icon: fontawesome/brands/twitter
    #   link: https://twitter.com/REPLACE_TWITTER_USERNAME
    # - icon: fontawesome/brands/linkedin
    #   link: https://www.linkedin.com/in/REPLACE_LINKEDIN_USERNAME/
nav:
- Home: index.md
- Quick Start: quick.md
# - Getting Started:
#   - Overview: getting-started/overview.md
#   - Setting Up Your API:
#     - FastAPI Sample App: getting-started/sample-app.md
#     - API Configuration: getting-started/api-configuration.md
#   - Registering Your Service:
#     - Register via Agentopia: getting-started/register-service.md
#     - service Stats Dashboard: getting-started/service-dashboard.md
#   - Quick Deployment Guide: getting-started/deployment-guide.md
- Using Agentopia Services:
  # - Overview: using-servives/overview.md
  - Wallet Setup: using-services/wallet-setup.md
  - Authentication:
    - Generate Signature: using-services/authentication/generate-signature.md
    - Managing Nonce: using-services/authentication/nonce.md
    - Create an API Key: using-services/authentication/create-api-key.md
  - Check Wallet Balance: using-services/check-balance.md
  - Use services:
    - Searching for a Service: using-services/search.md
    - Run services via Proxy API: using-services/run-proxy-api.md
  - Run services Directly: using-services/run-directly.md
- Selling via Agentopia:
  - Overview: selling/overview.md
  - Building a Service:
    - FastAPI Examples:
      - Using the `@service` Decorator: selling/service-decorator.md
      - Hello World! Service: selling/hello-world-service.md
    - Handle Holds: selling/handle-holds.md
  - Registration and Deployment:
    - Register Your Service: selling/register-service.md
- Smart Contracts: contracts.md
# - Community:
#   - Join the Community: community/join.md
#   - Contribute: community/contribute.md
# - About:
#   - What is Agentopia?: about/what-is-agentopia.md
#   - Contact Us: about/contact.md
